Repository t-erxleben/marbellous, pull requests merged in 2021-05, with the labels that each got.

#16 Color representaion
  demo/backend/BUILD
  demo/backend/include/Color.hpp
  demo/backend/include/Palette.hpp
  demo/backend/src/Color.cpp
  demo/backend/src/Palette.cpp
Labels: enhancement

#17 Gui Framework
  Notes/Design/GUI.md
Labels: documentation

#18 First version of an options class
  demo/backend/BUILD
  demo/backend/include/Color.hpp
  demo/backend/include/Options.hpp
  demo/backend/include/Palette.hpp
  demo/backend/src/Color.cpp
  demo/backend/src/Options.cpp
  demo/backend/src/Palette.cpp
Labels: enhancement

#19 Implementing Gui Mock
  WebFrontend/actions.js
  WebFrontend/favicon.ico
  WebFrontend/icons/arrow-right-solid.svg
  WebFrontend/icons/chalkboard-solid.svg
  WebFrontend/icons/empty.svg
  WebFrontend/icons/exchange-alt-solid.svg
  WebFrontend/icons/eye-dropper-solid.png
  WebFrontend/icons/eye-dropper-solid.svg
  WebFrontend/icons/image-regular.svg
  WebFrontend/icons/movement.svg
  WebFrontend/icons/palette-solid.svg
  WebFrontend/icons/question-solid.svg
  WebFrontend/icons/regular-rake-solid.svg
  WebFrontend/icons/sparkle-solid.png
  WebFrontend/icons/sparkle-solid.svg
  WebFrontend/icons/square-rake-solid.svg
  WebFrontend/icons/straight.svg
  WebFrontend/icons/undo-solid.svg
  WebFrontend/icons/wave.svg
  WebFrontend/index.html
  WebFrontend/stylesheet.css
Labels: enhancement

#22 Draw Circles with WebGL
  .gitignore
  demo/WORKSPACE
  demo/backend/BUILD
  demo/backend/CMakeLists.txt
  demo/backend/include/Renderer.hpp
  demo/backend/src/Color.cpp
  demo/backend/src/Renderer.cpp
  demo/backend/src/main.cpp
Labels: enhancement

#14 Implement PoC
  .gitignore
  demo/backend/CMakeLists.txt
  demo/backend/include/Color.hpp
  demo/backend/include/Options.hpp
  demo/backend/include/Palette.hpp
  demo/backend/include/Renderer.hpp
  demo/backend/src/Color.cpp
  demo/backend/src/Options.cpp
  demo/backend/src/Palette.cpp
  demo/backend/src/Renderer.cpp
  demo/backend/src/main.cpp
Labels: enhancement

#29 Add demo backend to frontend
  demo/backend/CMakeLists.txt
  demo/backend/src/Renderer.cpp
  demo/backend/src/main.cpp
  demo/frontend/actions.js
  demo/frontend/index.html
Labels: UI, enhancement

#32 UI fixes
  demo/backend/src/Renderer.cpp
  demo/frontend/actions.js
  demo/frontend/icons/fast-backward-solid.svg
  demo/frontend/icons/file-download-solid.svg
  demo/frontend/index.html
  demo/frontend/stylesheet.css
Labels: UI, bug

#38 Fix arrow head from rake tool tip
  demo/frontend/actions.js
Labels: UI, bug

#35 Automatic deployment and hosting on GitHub Pages
  .github/workflows/main.yml
  index.html
Labels: enhancement

#37 Refactor parts of demo and add new class strucutre
  backend/CMakeLists.txt
  backend/include/Color.hpp
  backend/include/Options.hpp
  backend/include/Palette.hpp
  backend/include/Point.hpp
  backend/include/Polygon.hpp
  backend/include/Scene.hpp
  backend/include/WGLContext.hpp
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/include/WGLVertex.hpp
  backend/src/Color.cpp
  backend/src/Options.cpp
  backend/src/Palette.cpp
  backend/src/main.cpp
Labels: enhancement

#49 feature/#20 sidebar menu
  demo/frontend/actions.js
  demo/frontend/index.html
  demo/frontend/stylesheet.css
Labels: UI, enhancement

#64 Rename color rake to color grid
  demo/frontend/actions.js
  demo/frontend/index.html
Labels: UI, bug

#63 Add Readme and legal notice for mapbox/earcut
  LICENSE
  README.MD
  backend/include/Color.hpp
  backend/include/Palette.hpp
  demo/backend/include/Color.hpp
  demo/backend/include/Palette.hpp
  demo/frontend/index.html
  demo/frontend/stylesheet.css
Labels: documentation

#65 Add No-JS warning and touch not supported allert
  demo/frontend/actions.js
  demo/frontend/index.html
Labels: documentation
