Repository t-erxleben/marbellous, pull requests merged in 2021-09, with the labels that each got.

#173 Feature/opengl tweaks
  backend/CMakeLists.txt
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLRenderer.hpp
  backend/src/WGLFilter.cpp
  backend/src/WGLRakeRenderer.cpp
  backend/src/WGLRenderer.cpp
  backend/src/WGLSceneRenderer.cpp
  backend/src/main.cpp
Labels: enhancement

#192 Make drawing area max size without srcolling
  frontend/dist/stylesheet.css
Labels: bug

#190 Translate rake info graphic
  frontend/dist/imgs/rake.svg
  frontend/src/rake.drawio
Labels: bug

#188 Handle zero sized wave rake
  frontend/src/index.js
Labels: bug

#183 Polishing
  README.MD
  frontend/dist/index.html
  frontend/dist/stylesheet.css
  frontend/src/index.js
Labels: bug, UI

#191 fix/remove debug logs
  backend/src/main.cpp
  frontend/dist/index.html
  frontend/dist/stylesheet.css
  frontend/src/index.js
  frontend/webpack.config.js.in
Labels: enhancement

#187 Add corelation between vertex count and resolution
  backend/CMakeLists.txt
  backend/include/Color.hpp
  backend/include/Options.hpp
  backend/include/Point.hpp
  backend/include/Polygon.hpp
  backend/include/Scene.hpp
  backend/src/Color.cpp
  backend/src/Options.cpp
  backend/src/Polygon.cpp
  backend/src/main.cpp
  frontend/dist/stylesheet.css
Labels: enhancement

#176 Feature/#143 docs
  .gitignore
  backend/Documentation.md
  backend/Doxyfile
  backend/html/Pictures/10000000000002000000020039EDA5960216C6DE.png
  backend/html/Pictures/100002010000009000000090B0B2EFA457698CCA.png
  backend/html/Pictures/10000201000000B4000000CA18287C510212EE2D.png
  backend/html/Pictures/10000201000000E10000005E3451440A90FE5318.png
  backend/html/Pictures/100002010000014A0000005A391F0C68A8488761.png
  backend/html/Pictures/100002010000014A0000008047600BF75023824B.png
  backend/html/Pictures/100002010000014A000000809F127A67DC81E8E9.png
  backend/html/Pictures/100002010000014A0000014A51392247F561327C.png
  backend/html/Pictures/1000020100000164000000607CF209F4AC769F50.png
  backend/html/Pictures/10000201000001C2000000BCCC3536B3CA7993D7.png
  backend/html/Pictures/10000201000002BD000001737179BC21251A4CE6.png
  backend/html/Pictures/1000020100000386000001C40AEDF40938C050E1.png
  backend/html/Pictures/10000201000007370000045991F78369D3A502BF.png
  backend/html/info.md
  backend/include/Color.hpp
  backend/include/Options.hpp
  backend/include/Palette.hpp
  backend/include/Point.hpp
  backend/include/Polygon.hpp
  backend/include/Scene.hpp
  backend/include/WGLContext.hpp
  backend/include/WGLFilter.hpp
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/include/WGLVertex.hpp
  backend/src/main.cpp
Labels: documentation
