Repository t-erxleben/marbellous, pull requests merged in 2021-07, with the labels that each got.

#124 normalized rake input ||(x,y)|| == speed
  backend/src/main.cpp
  frontend/src/index.js
Labels: UI, bug

#125 Fix downlowd pixel error
  LICENSE
  Notes/Settings.md
  README.MD
  backend/CMakeLists.txt
  backend/src/main.cpp
  frontend/package.json
  frontend/src/index.js
  frontend/webpack.config.js.in
Labels: bug

#130 Sprinkler
  backend/CMakeLists.txt
  backend/include/WGLContext.hpp
  backend/src/main.cpp
  frontend/dist/apple-touch-icon.png
  frontend/dist/fav-raw.png
  frontend/dist/favicon.ico
  frontend/dist/favicon.png
  frontend/dist/index.html
  frontend/dist/mstile-144x144.png
  frontend/dist/stylesheet.css
  frontend/src/index.js
  frontend/webpack.config.js.in
Labels: enhancement

#145 deactivate post-processing
  backend/src/WGLRakeRenderer.cpp
Labels: bug
