Repository t-erxleben/marbellous, pull requests merged in 2021-06, with the labels that each got.

#76 Fix drawing artefacts
  backend/src/Polygon.cpp
Labels: bug, enhancement

#75 Added noscript msg to actual frontend
  frontend/actions.js
  frontend/index.html
  frontend/stylesheet.css
Labels: UI

#89 Dynamic vertice count
  backend/include/Point.hpp
  backend/include/Polygon.hpp
  backend/include/Scene.hpp
  backend/src/Polygon.cpp
  backend/src/main.cpp
Labels: enhancement

#87 Flip image output
  backend/include/WGLSceneRenderer.hpp
  backend/src/WGLSceneRenderer.cpp
  backend/src/main.cpp
  frontend/actions.js
Labels: UI

#90 Store settings in browser
  frontend/actions.js
  frontend/index.html
  frontend/stylesheet.css
Labels: UI

#95 Feature/#46 rake rendering
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/src/WGLRakeRenderer.cpp
  backend/src/WGLRenderer.cpp
  backend/src/WGLSceneRenderer.cpp
Labels: enhancement

#88 Rake input format
  LICENSE
  Notes/Settings.md
  README.MD
  backend/CMakeLists.txt
  backend/src/main.cpp
  frontend/dist/favicon.ico
  frontend/dist/icons/arrow-right-solid.svg
  frontend/dist/icons/chalkboard-solid.svg
  frontend/dist/icons/empty.svg
  frontend/dist/icons/exchange-alt-solid.svg
  frontend/dist/icons/eye-dropper-solid.png
  frontend/dist/icons/eye-dropper-solid.svg
  frontend/dist/icons/fast-backward-solid.svg
  frontend/dist/icons/file-download-solid.svg
  frontend/dist/icons/image-regular.svg
  frontend/dist/icons/movement.svg
  frontend/dist/icons/palette-solid.svg
  frontend/dist/icons/question-solid.svg
  frontend/dist/icons/regular-rake-solid.svg
  frontend/dist/icons/sparkle-solid.png
  frontend/dist/icons/sparkle-solid.svg
  frontend/dist/icons/square-rake-solid.svg
  frontend/dist/icons/straight.svg
  frontend/dist/icons/undo-solid.svg
  frontend/dist/icons/wave.svg
  frontend/dist/index.html
  frontend/dist/stylesheet.css
  frontend/package.json
  frontend/src/index.js
  frontend/src/rake_syntax.pegjs
  frontend/webpack.config.js.in
Labels: UI, documentation

#107 Snapshot is saved when enabling storing
  frontend/dist/index.html
  frontend/src/index.js
Labels: UI, enhancement

#106 Ui repairings
  backend/include/Scene.hpp
  backend/src/main.cpp
  frontend/dist/index.html
  frontend/dist/stylesheet.css
  frontend/src/index.js
Labels: UI, bug

#105 Finish first raking version
  backend/include/Palette.hpp
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/src/WGLRakeRenderer.cpp
  backend/src/WGLSceneRenderer.cpp
  backend/src/main.cpp
Labels: bug, enhancement

#122 Fix nail transfer
  backend/src/main.cpp
  frontend/src/index.js
Labels: bug
