Repository t-erxleben/marbellous, pull requests merged in 2021-08, with the labels that each got.

#146 fix invalid uniform set while init
  backend/src/Options.cpp
Labels: bug

#147 Fix/#144 duplicated view
  backend/include/WGLRakeRenderer.hpp
  backend/src/WGLRakeRenderer.cpp
Labels: enhancement

#151 Feature/#127 resolution
  backend/include/WGLContext.hpp
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/src/WGLContext.cpp
  backend/src/WGLRakeRenderer.cpp
  backend/src/WGLRenderer.cpp
  backend/src/WGLSceneRenderer.cpp
  backend/src/main.cpp
Labels: enhancement

#148 Add ratios for sparkle (and simple Grid drop)
  backend/include/Color.hpp
  backend/include/Palette.hpp
  backend/include/Point.hpp
  backend/include/Polygon.hpp
  backend/include/Scene.hpp
  backend/include/WGLRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/src/Color.cpp
  backend/src/Palette.cpp
  backend/src/Polygon.cpp
  backend/src/WGLSceneRenderer.cpp
  backend/src/main.cpp
  frontend/dist/index.html
  frontend/dist/stylesheet.css
  frontend/src/index.js
Labels: enhancement, UI

#157 add rake undo function
  backend/include/WGLRakeRenderer.hpp
  backend/src/WGLRakeRenderer.cpp
  backend/src/main.cpp
  frontend/dist/index.html
  frontend/dist/stylesheet.css
  frontend/src/index.js
Labels: enhancement

#158 Separate postprocessing functionality from drawing
  backend/include/Options.hpp
  backend/include/WGLFilter.hpp
  backend/include/WGLRakeRenderer.hpp
  backend/include/WGLSceneRenderer.hpp
  backend/src/Options.cpp
  backend/src/WGLFilter.cpp
  backend/src/WGLRakeRenderer.cpp
  backend/src/WGLSceneRenderer.cpp
  backend/src/main.cpp
  frontend/dist/index.html
  frontend/src/index.js
  frontend/webpack.config.js.in
Labels: enhancement

#161 add resize for conv when resizing scene renderer
  backend/src/WGLSceneRenderer.cpp
Labels: bug

#155 Add UI for resizing
  frontend/dist/index.html
  frontend/src/index.js
Labels: enhancement, UI

#163 activate post processing only for color drawing
  backend/src/WGLSceneRenderer.cpp
Labels: bug

#171 Fix periode length for wave rakes
  backend/include/WGLRakeRenderer.hpp
  frontend/src/index.js
Labels: bug

#170 Add proper storage for pallet switch
  backend/src/Options.cpp
  backend/src/main.cpp
  frontend/src/index.js
Labels: bug, UI
